### ISSUE TITLE
Default document language is Français

### ISSUE THREAD

**Issue by poandlsl** [xwikisas/application-onlyoffice-connector#11]
When creating a new document via Xwiki, the default document language is always set to Français (French), despite our Xwiki language settings being set to English.  This issue only appears when using the Xwiki OnlyOffice connector.  Connecting to the same Document Server from another application (Nextcloud) results in English being the default language of new documents, as expected.

OnlyOffice Connector v1.4
Document Server 5.4.1

![image](https://user-images.githubusercontent.com/26942983/68130264-0b2f6000-fee9-11e9-8445-446c2afba92a.png)

![image](https://user-images.githubusercontent.com/26942983/68130273-0ff41400-fee9-11e9-80fe-310dc125f554.png)

**Comment by acotiuga** [comment]
An example empty file is used upon Only Office document creation. That default `docx` document has the default language set to `FR`, while the `pptx` and `xlsx` are set to `EN`. For this specific issue, all we can do at this point is to save the document with language set to `EN`, but this won't bring any flexibility and no matter what language is your wiki, you will still see the `EN` as the default language. The same issue should be present on other platforms for any other language when the default of the document is `EN`.
