### ISSUE TITLE
"HelloWorld" box appears

### ISSUE THREAD

**Issue by ane-gabriela** [xwikisas/application-onlyoffice-connector#17]
Steps to reproduce:

1. Access a page
2. Click on the Attachments tab
3. Click on New Document / New Spreadsheet /  New Presentation

Expected results: The creation boxes appear.

Actual results: "HelloWorld" box appears - sometimes for 1-2 seconds, other times for 3-4 seconds.

![HelloWorld](https://user-images.githubusercontent.com/40691112/68765102-b1cfdb00-0624-11ea-9dea-984355aa7089.jpg)

![HelloWorld2](https://user-images.githubusercontent.com/40691112/68765109-b4323500-0624-11ea-91ce-a1ca28c1cad2.jpg)

**Comment by snazare** [comment]
closing as this issue is inactive and does not reproduce anymore.
