### ISSUE TITLE
Edit with OnlyOffice buttons are missing.

### ISSUE THREAD

**Issue by poandlsl** [xwikisas/application-onlyoffice-connector#27]
After upgrading XWiki to 14.6, the edit with OnlyOffice buttons next to attachments no longer appear.  If the tomcat service is restarted (thus restarting XWiki), the buttons will appear next to attachments, but only once, and only for the first user to load the page.  After that, the buttons do not appear for all users.

XWiki version: 14.6
OnlyOffice connector version: 1.6

**Comment by poandlsl** [comment]
We have discovered a workaround.
If the user clicks the Attachments tab, the Edit with OnlyOffice buttons do not appear.  However, if the user clicks to another tab (for example the History tab) then clicks back to the Attachments tab, the Edit with OnlyOffice buttons _do_ appear.

**Comment by mflorea** [comment]
@trrenty can you check this? Thanks.

**Comment by Tragen** [comment]
Same here now with newest xwiki

**Comment by Tragen** [comment]
> We have discovered a workaround. If the user clicks the Attachments tab, the Edit with OnlyOffice buttons do not appear. However, if the user clicks to another tab (for example the History tab) then clicks back to the Attachments tab, the Edit with OnlyOffice buttons _do_ appear.

For me, this isn't working.
