### ISSUE TITLE
Sometimes after editing a file and clicking Save & View a "Leave site?" message box appears

### ISSUE THREAD

**Issue by ane-gabriela** [xwikisas/application-onlyoffice-connector#30]
This issue reproduces only from time to time, I couldn't find a clear patterner.

After editing a document and clicking Save & View, sometimes, a message box appears

![Screenshot_4](https://user-images.githubusercontent.com/40691112/189956435-08fc9b27-6715-4766-afd8-70b0b44a6011.jpg)

Environment: Windows 11, XWiki 14.4.3 and 14.7, OnlyOffice Connector Application 2.0-rc-2 used (Advanced search EXTENSION ID: com.xwiki.onlyoffice-connector:application-onlyoffice-connector-ui, Version - 2.0-rc-2), https://onlyoffice.devxwiki.com/ (v7.0.1), Chrome 105

**Comment by trrenty** [comment]
The issue manifested when the user would leave the page before the modified data was sent to the OnlyOffice server (when auto-saving). The user will now have the "Save and View" button disabled while he edits the file until the OnlyOffice client will notify us  that the changes were sent successfully.
