### ISSUE TITLE
Error with OnlyOffice 7.5

### ISSUE THREAD

**Issue by Tragen** [xwikisas/application-onlyoffice-connector#38]
When I update to OnlyOffice 7.5, I cannot open documents anymore.
Can you check what's wrong with the connector?

**Comment by snazare** [comment]
Kindly note that the Only Office Connector is currently compatible with document server 7.0: https://store.xwiki.com/xwiki/bin/view/Extension/OnlyOfficeConnectorApplication#description

**Comment by Tragen** [comment]
I've updated to 8.0 and get the error message: "Unable to push attachment up to OnlyOffice server"
With 7.3 it was working. I try to find why I get this error.

**Comment by Tragen** [comment]
I got some CORS errors which I fixed, now I get something like "Tables loading" and then another error.
![image](https://github.com/xwikisas/application-onlyoffice-connector/assets/1700241/c62c5661-be20-4f69-844f-3ea52722cd84)
which means "Download failed"

**Comment by trrenty** [comment]
Hmm. From my investigation for the #40 issue, the problem on versions 7.2+ was that the JWT was enabled by default which meant that the communication between XWiki and OnlyOfficeServer had to take that into consideration. 

Did you manually disable the JWT when configuring the onlyoffice document server? 

Alternatively, on the latest version of our integration, you can add the server secret key in the administration page (if you configured it) so that the JWTs can be added to the requests to the OO server. Here is the OnlyOffice documentation for configuring the JWT. https://helpcenter.onlyoffice.com/installation/docs-configure-jwt.aspx

I recommend trying the second option

**Comment by Tragen** [comment]
I installed the update OO 8.0.1 and set the JWT tokes. I've looked at the administration page for the OO connector but there is no option for the token there.

**Comment by trrenty** [comment]
Thats odd. There should be a `server secret` property inside the Administration page. Are you sure you have the latest version of Application OnlyOffice Integration installed? 2.2.0

After you install the application, if you try to create/edit a document you should receive the following error message:
![image](https://github.com/xwikisas/application-onlyoffice-connector/assets/45433221/1db4ac05-bf39-44e2-abca-13c8906eb396)

To solve this, you should go to the administration page and fill in the `server secret` parameter with the secret configured on your only office document server. In my case, I'm running v8.0 of the OnlyOffice document server using docker.

This is the command that I used:

```
sudo docker run -i -t -d -p 80:80 --restart=always     
  -v /app/onlyoffice/DocumentServer/logs:/var/log/onlyoffice      
  -v /app/onlyoffice/DocumentServer/data:/var/www/onlyoffice/Data      
  -v /app/onlyoffice/DocumentServer/lib:/var/lib/onlyoffice     
  -v /app/onlyoffice/DocumentServer/db:/var/lib/postgresql 
  -e JWT_SECRET=my_jwt_secret onlyoffice/documentserver
```
The secret was configured using the `JWT_SECRET` variable. The value I set to it is the same value I input in the administration section.
![image](https://github.com/xwikisas/application-onlyoffice-connector/assets/45433221/45696bad-12b9-478e-a030-6a8c32afdf2e)

After saving, when I try to edit the previous document, it works as intended.
![image](https://github.com/xwikisas/application-onlyoffice-connector/assets/45433221/2a88a3cf-396f-45c6-b587-951d8acbe53f)

**Comment by Tragen** [comment]
I've installed OnlyOffice with the repo, I don't use the docker container.
I don't have the option to enter the JWT token
![image](https://github.com/xwikisas/application-onlyoffice-connector/assets/1700241/2da43314-ec55-4f2e-9e3c-708e356aeff4)
The current version 2.2.0 is installed
![image](https://github.com/xwikisas/application-onlyoffice-connector/assets/1700241/6fa8dea1-b376-4e01-adb1-ec5cd68624b8)

**Comment by Tragen** [comment]
I removed the OO extension and reinstalled it, now I can enter the serversecret.
I will try again with OO8

**Comment by Tragen** [comment]
Whatever I do with OO8, it doesn't work.
Now I get CORS errors and this error
![image](https://github.com/xwikisas/application-onlyoffice-connector/assets/1700241/7ca2a9c1-c3a9-41ac-ba08-09b82100ca79)

I've tried everything to solve the CORS error but whatever I do, I cannot get it to work.
I've put
        add_header 'Access-Control-Allow-Origin' '*';
at every location I could find

**Comment by trrenty** [comment]
To avoid having trouble with the CORS policy, I used a browser extension `CORS Everywhere` (on firefox).

From what I read, the onlyoffice document server does not provide an explicit way of setting the response headers. So you would either have to deploy the server on a different domain or set up a proxy at the same origin (and port) as your XWiki instance.

**Comment by Tragen** [comment]
Currently I have it running on different computers with the same domain name and different ports.
I will give it a new domain name and check again if it's working.
