### ISSUE TITLE
Store.xwiki.com:443 failed to respond

### ISSUE THREAD

**Issue by dannyscarborough** [xwikisas/application-onlyoffice-connector#5]
Hello,

I’m having trouble accessing https://store.xwiki.com on my XWiki instance. I'm looking to use your OnlyOffice Connector but I can't find the extension in XWiki. Can you offer any advice? I've have the following setup.

**Xwiki version**: 9.11.1
**Java**: jre1.8.0_191 / jdk1.8.0_191
**Server**: Windows server 2012 R2

Catalina.bat:

```
> :gotJsseOpts
> set “JAVA_OPTS=%JAVA_OPTS% %JSSE_OPTS%”
> set “JAVA_OPTS=”-Dhttp.proxyHost=PROXYIP -Dhttp.proxyPort=8080"
> set “JAVA_OPTS=”-Dhttps.proxyHost=PROXYIP -Dhttps.proxyPort=443"
```

Catalina.properties

```
> #http proxy host setup
> http.proxyHost=PROXYIP
> http.proxyPort=8080
> https.proxyHost=PROXYIP
> https.proxyPort=443
```

When I run the extension update I receive the following errors:

```
> Caused by: class java.io.IOException: Failed to request [https://store.xwiki.com/xwiki/rest/repository/extensions/yannflory%3Arealtime-netflux-frontend/versions/1.15 1]
> at org.xwiki.extension.repository.xwiki.internal.XWikiExtensionRepository.getRESTResource(XWikiExtensionRepository.java:247)
> at org.xwiki.extension.repository.xwiki.internal.XWikiExtensionRepository.getRESTObject(XWikiExtensionRepository.java:305)
> at org.xwiki.extension.repository.xwiki.internal.XWikiExtensionRepository.resolve(XWikiExtensionRepository.java:350)
> at org.xwiki.extension.repository.xwiki.internal.XWikiExtensionRepository.resolve(XWikiExtensionRepository.java:340)
> at org.xwiki.extension.repository.internal.DefaultExtensionRepositoryManager.resolve(DefaultExtensionRepositoryManager.java:288)
> at org.xwiki.extension.job.internal.AbstractInstallPlanJob.resolveExtension(AbstractInstallPlanJob.java:790)
> at org.xwiki.extension.job.internal.AbstractInstallPlanJob.installExtension(AbstractInstallPlanJob.java:750)
> at org.xwiki.extension.job.internal.AbstractInstallPlanJob.installExtension(AbstractInstallPlanJob.java:309)
> at org.xwiki.extension.job.internal.AbstractInstallPlanJob.installExtension(AbstractInstallPlanJob.java:277)
> at org.xwiki.extension.job.internal.AbstractInstallPlanJob.start(AbstractInstallPlanJob.java:208)
> at org.xwiki.extension.job.internal.InstallPlanJob.runInternal(InstallPlanJob.java:88)
> at org.xwiki.job.AbstractJob.runInContext(AbstractJob.java:206)
> at org.xwiki.job.AbstractJob.run(AbstractJob.java:189)
> at org.xwiki.extension.job.internal.InstallJob.runInternal(InstallJob.java:112)
> at org.xwiki.job.AbstractJob.runInContext(AbstractJob.java:206)
> at org.xwiki.job.AbstractJob.run(AbstractJob.java:189)
> at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
> at java.lang.Thread.run(Unknown Source)
> Caused by: class org.apache.http.NoHttpResponseException: store.xwiki.com:443 failed to respond
> at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:141)
> at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
> at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
> at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
> at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:165)
> at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
> at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
> at org.apache.http.impl.execchain.MainClientExec.createTunnelToTarget(MainClientExec.java:473)
> at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:398)
> at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
> at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
> at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
> at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
> at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
> at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
> at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
> at org.xwiki.extension.repository.xwiki.internal.XWikiExtensionRepository.getRESTResource(XWikiExtensionRepository.java:244)
> at org.xwiki.extension.repository.xwiki.internal.XWikiExtensionRepository.getRESTObject(XWikiExtensionRepository.java:305)
> at org.xwiki.extension.repository.xwiki.internal.XWikiExtensionRepository.resolve(XWikiExtensionRepository.java:350)
> at org.xwiki.extension.repository.xwiki.internal.XWikiExtensionRepository.resolve(XWikiExtensionRepository.java:340)
> at org.xwiki.extension.repository.internal.DefaultExtensionRepositoryManager.resolve(DefaultExtensionRepositoryManager.java:288)
> at org.xwiki.extension.job.internal.AbstractInstallPlanJob.resolveExtension(AbstractInstallPlanJob.java:790)
> at org.xwiki.extension.job.internal.AbstractInstallPlanJob.installExtension(AbstractInstallPlanJob.java:750)
> at org.xwiki.extension.job.internal.AbstractInstallPlanJob.installExtension(AbstractInstallPlanJob.java:309)
> at org.xwiki.extension.job.internal.AbstractInstallPlanJob.installExtension(AbstractInstallPlanJob.java:277)
> at org.xwiki.extension.job.internal.AbstractInstallPlanJob.start(AbstractInstallPlanJob.java:208)
> at org.xwiki.extension.job.internal.InstallPlanJob.runInternal(InstallPlanJob.java:88)
> at org.xwiki.job.AbstractJob.runInContext(AbstractJob.java:206)
> at org.xwiki.job.AbstractJob.run(AbstractJob.java:189)
> at org.xwiki.extension.job.internal.InstallJob.runInternal(InstallJob.java:112)
> at org.xwiki.job.AbstractJob.runInContext(AbstractJob.java:206)
> at org.xwiki.job.AbstractJob.run(AbstractJob.java:189)
> at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
> at java.lang.Thread.run(Unknown Source)
```

**Comment by acotiuga** [comment]
Hello @dannyscarborough! I am currently investigating the issue and it looks that from time to time it fails, but overall I am able to get the updates. I would suggest you to try again, until we manage to fix this flickering issue.

**Comment by dannyscarborough** [comment]
> Hello @dannyscarborough! I am currently investigating the issue and it looks that from time to time it fails, but overall I am able to get the updates. I would suggest you to try again, until we manage to fix this flickering issue.

Thanks for getting back to me @acotiuga. Are you saying the issue is at your end? Do you have anyway I could manually download the OnlyOffice Connector extension to trial whilst the issue is being resolved?

**Comment by acotiuga** [comment]
The OnlyOffice Connector is not installed by default in XWiki, so you have to do it manually. Check https://store.xwiki.com/xwiki/bin/view/Extension/OnlyOfficeConnectorApplication#installation for documentation and installation guide (installation tab). Hope this helps!

**Comment by acotiuga** [comment]
@dannyscarborough are you able to access store.xwiki.com from the same browser, for the same windows machine where you're starting XWiki?

**Comment by dannyscarborough** [comment]
> @dannyscarborough are you able to access store.xwiki.com from the same browser, for the same windows machine where you're starting XWiki?

Yes, I have no problem accessing the web page. Our proxy is also configured for unauthenticated access too.

**Comment by acotiuga** [comment]
Try to do the following test: 
From your XWiki instance do some external calls and see if they get through.
Write $xwiki.getURLContent("http://www.google.com") in a wiki page and see what you get.
Try some multiple versions with/without https and then something from store.xwiki.com.
If the instance does not have outside access, then the proxy parameters are probably to blame.

**Comment by dannyscarborough** [comment]
@acotiuga Thanks again for your help with this, I believe it's probably an incorrect proxy parameter set on our instance. I just wanted to check does my XWiki need to be a HTTPS site to access this content?

Regarding the proxy parameters I have them set all over the place but I'm unsure which one it is actually using.

Like mentioned above I have them set in Catalina.bat and Catalina.properties but I've also set them in the Java configuration itself (“Control Panel”, Tab “General”, in the middle there is a button “Network Settings”) as well as in the windows environment variables. Does it need to be in all of these places?

In the official documentation it says that it just needs configuring in catalina.bat
https://www.xwiki.org/xwiki/bin/view/Documentation/AdminGuide/Installation/#HRunningXWikibehindaproxyserver

**Comment by dannyscarborough** [comment]
It turns out the issue was related to our proxy configuration, we currently use HTTPS scanning which scans and then replaces site certs. We have added store.xwiki to an exception list and it started working. Now I just need to get our only office document server working :confused:

Thanks for all your help.
