### ISSUE TITLE
11.3: can't download JS...

### ISSUE THREAD

**Issue by polx** [xwikisas/application-onlyoffice-connector#7]
Today I installed the freshly made 11.3 and pulled the onlyoffice connector.
I installed license... no trouble.
I uploaded a docx attachment and clicked on the little stack of 3 squares to edit it. I obtained the screenshot attached.

In the console:
The script from “http://10.90.0.114:8080/xwiki/bin/viewattachrev/XWikiOnlyOfficeCode/XooEdit/xwiki-onlyoffice.js” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type.[Learn More]

and indeed http://10.90.0.114:8080/xwiki/bin/viewattachrev/XWikiOnlyOfficeCode/XooEdit/xwiki-onlyoffice.js shows an HTML file (choice of attachment versions) whereas it is called as a script.

paul

**Comment by polx** [comment]
<img width="1092" alt="Screenshot 2019-05-02 at 17 07 41" src="https://user-images.githubusercontent.com/818835/57086188-f5ed3500-6cfd-11e9-9f17-0ff1c3e95f2c.png">

**Comment by polx** [comment]
This is caused by the call to the URL http://127.0.0.1:8080/xwiki/bin/downloadrev/XWikiOnlyOfficeCode/XooEdit/xwiki-onlyoffice.js?rev=1.1?cb=1556810732367 which is malformed as it has two question marks.

* in 11.3: this redirects to http://127.0.0.1:8080/xwiki/bin/viewattachrev/XWikiOnlyOfficeCode/XooEdit/xwiki-onlyoffice.js
* in 11.1: this loads the appropriate (and sole) version

**Comment by polx** [comment]
This is caused by https://github.com/xwikisas/application-onlyoffice-connector/blob/master/application-onlyoffice-connector-ui/src/main/resources/XWikiOnlyOfficeCode/XooEdit.xml#L155 : `require(["$doc.getAttachmentURL('xwiki-onlyoffice.js')" + '?cb=' + new Date().getTime()], function (oojs) {...`

I do not see a reason to keep the cb parameter.

paul

**Comment by polx** [comment]
A dialogue on XWiki chat shows that this change is justified by [XWIKI-15450](https://jira.xwiki.org/browse/XWIKI-15450) which was indeed deployed with 11.3.
A potential fix has been requested as [XWIKI-16378](https://jira.xwiki.org/browse/XWIKI-16378) however we should also have a fix of the app.

**Comment by polx** [comment]
Branch [issue-7-no-two-url-params](https://github.com/xwikisas/application-onlyoffice-connector/tree/issue-7-no-two-url-params) created with a fix.
paul

**Comment by mflorea** [comment]
@polx looks good.

**Comment by acotiuga** [comment]
@polx you can commit the changes from your branch.

**Comment by polx** [comment]
Cool. This is merged.
Ok to release version 1.4 then?
paul
